# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmkitjournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
