"""
Django settings for mmkit2 project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from mmkit2.conf import import_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.environ.get('BASE_DIR')

APP_ENV = os.environ.get('APP_ENV', 'prod')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'crispy_forms',
    'mmkitarchive',
    'mmkitcommon',
    'mmkitjournal'
]

import_settings(
    globals(),
    [r'*@mmkit', 'common', APP_ENV, 'local', '{}-local'.format(APP_ENV.lower())],
    INSTALLED_APPS,
    ('INSTALLED_APPS', )
)
