# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории (не более 64 символов, должно быть уникальным)', max_length=64, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория элемента архива',
                'verbose_name_plural': 'категории элементов архива',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента (не более 255 символов, должно быть уникальным)', max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Развёрнутое описание элемента (необязательно)', verbose_name='описание')),
                ('created', models.DateField(help_text='Дата создания элемента (необязательно)', null=True, verbose_name='дата создания')),
                ('author', models.CharField(help_text='Автор(ы) элемента', max_length=255, verbose_name='автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mmkitarchive.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'элемент архива',
                'verbose_name_plural': 'элементы архива',
                'default_permissions': (),
            },
        ),
    ]
