# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmkitarchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='mmkitarchive.Category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateField(db_index=True, help_text='Дата создания элемента (необязательно)', null=True, verbose_name='дата создания'),
        ),
    ]
