# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmkitarchive', '0002_auto_20160617_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='linked',
            field=models.ManyToManyField(related_name='_item_linked_+', to='mmkitarchive.Item', verbose_name='связанные элементы'),
        ),
    ]
